spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=HomeSync;encrypt=true;trustServerCertificate=true;
    username: root3
    password: 1234
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
